export const ADD_COLUMN = 'ADD_COLUMN';
export const ADD_TASK_TO_COLUMN = 'ADD_TASK_TO_COLUMN';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASKS_IN_COLUMN = 'UPDATE_TASKS_IN_COLUMN';
export const REORDER_TASKS_IN_COLUMN = 'REORDER_TASKS';
// export const GET_COLUMNS = 'GET_COLUMNS';